sudo: required
services:
    - docker

before_install:
    - docker build -t mosh2018/docker -f Dockerfile.dev .

script:
    - docker run -e CI=true mosh2018/docker npm run test

deploy:
    provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "eu-central-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-149501274876"
    bucket_path: "docker"
    on:
        branch: master
